name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip wget curl \
            openjdk-17-jdk \
            python3-pip \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            cmake libffi-dev libssl-dev

      - name: Set Java 17
        run: |
          JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH
          java -version

      - name: Install Buildozer
        run: |
          python3 -m pip install --user --upgrade pip
          python3 -m pip install --user buildozer cython==0.29.36

      - name: Install Android SDK
        run: |
          mkdir -p "$HOME/.buildozer/android/platform"
          cd "$HOME/.buildozer/android/platform"

          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip

          mkdir -p cmdline-tools
          unzip -q commandlinetools-linux-11076708_latest.zip -d cmdline-tools

          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          rm commandlinetools-linux-11076708_latest.zip

          export ANDROIDSDK="$HOME/.buildozer/android/platform/android-sdk"
          mkdir -p "$ANDROIDSDK"

          export PATH="$HOME/.buildozer/android/platform/cmdline-tools/latest/bin:$ANDROIDSDK/platform-tools:$PATH"

          yes | sdkmanager --sdk_root="$ANDROIDSDK" --licenses

          sdkmanager --sdk_root="$ANDROIDSDK" \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"

      - name: Build APK
        run: |
          export ANDROIDSDK="$HOME/.buildozer/android/platform/android-sdk"
          export ANDROID_HOME="$ANDROIDSDK"
          export PATH="$HOME/.local/bin:$ANDROIDSDK/platform-tools:$ANDROIDSDK/build-tools/35.0.0:$PATH"

          buildozer android debug

      - name: Check APK
        run: |
          ls -lah bin/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mymusic-apk
          path: bin/*.apk
